name = "MKtest"
uuid = "eac4f1b0-fea5-4d5c-b218-523869339fe7"
authors = ["Jes√∫s Murga-Moreno", "Lawrence Uricchio", "David Enard"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastaIO = "a0c94c4b-ebed-5953-b5fc-82fe598ac79f"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ParallelUtilities = "fad6cfc8-4f83-11e9-06cc-151124046ad0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
